### ISSUE TITLE
Исправить положение курсора ввода текста

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#11]
Положение курсора ввода текста некорректно устанавливает при добавлении новых сообщений спама.
![image](https://github.com/peterarsentev/dionea_bot/assets/86091103/cc3c0f7b-f8a5-4265-ada5-5f6659ba2b4b)
Должно быть строго слева вверху у края как и на всех веб ресурсах.

**Comment by peterarsentev** [comment]
Done. Close it.
