### ISSUE TITLE
Добавить цветовую или текстовую индикацию статуса добавляемого сообщения спама

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#12]
Например если сообщение спама успешно прошло проверку ботом, то вывести индикацию, что
ключевые слова из данного спам сообщения уже есть в базе бота и бот этот спам фиксирует.
И наоборот, если бот не задетектил данный спам, то вывести индикацию, что
данное сообщение обработано и добавлено в базу.

**Comment by peterarsentev** [comment]
Сделал.  Перенес на главную страницу.
![image](https://github.com/peterarsentev/dionea_bot/assets/694978/a5f9e27e-8eae-4989-a855-7cd2b4f13786)
