### ISSUE TITLE
Добавить в историю обнаруженных спам сообщений никнейм пользователя

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#13]
В истории обнаруженных спам сообщений нужно добавить никнейм пользователя который писал спам.

Никнейм должен располагаться под названием чата где был обнаружен спам, и иметь вид @имя_пользователя
затем должно идти двоеточие и далее текст спам сообщения.

Пример:

job4j.ru 27.04.2024 09:04
@имя_пользователя : Обучение. Писать в личку.

![image](https://github.com/peterarsentev/dionea_bot/assets/86091103/3e55bb39-731f-4c72-8776-2fd9343cd50e)

**Comment by peterarsentev** [comment]
Done it. Closed.
