### ISSUE TITLE
Исправить опечатки в тексте

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#18]
При проверке сообщения на спам в всплывающем сообщении в двух словах есть опечатки:
содрежит -> содержит
замены -> заменены

 
![image](https://github.com/peterarsentev/dionea_bot/assets/86091103/6101e139-aba6-4569-a6dc-1c46a07463cf)

Пожалуйста исправьте.

**Comment by peterarsentev** [comment]
Поправил.
