### ISSUE TITLE
Удаление собственных сообщений бота dionea

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#2]
Возможно стоит добавить удаление собственных сообщений бота dionea после обнаружения спам сообщений.
Т.е сейчас через 10 секунд спам сообщение удаляется, следом за ним сделать удаление сообщения об обнаружении.
Таким образом будет достигнута полная чистота чата телеграмм.

**Comment by peterarsentev** [comment]
Сделано. Спасибо.
