### ISSUE TITLE
Добавить проверку на добросовестного пользователя

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/dionea_bot#20]
Считаю, что уменьшить количество ложных срабатываний поможет дополнительная таблица с добросовестными пользователями. В эту таблицу должны быть добавлены никнеймы пользователей которые уже писали сообщения и они не были отмечены другими пользователями как спам (не был вызван антиспам бот на их сообщение). 
При срабатывании триггера на ключевые слова, антиспам бот должен проводить дополнительную проверку на то находится ли никнейм данного пользователя в списке добросовестных пользователей если да, то не удалять такие сообщения.
Конечно данную фичу пользователи могут заабузить во вред, но можно ещё подумать над дополнительными проверками и условиями.

**Comment by peterarsentev** [comment]
Поправил.
