### ISSUE TITLE
Необработка спама

### ISSUE THREAD

**Issue by leyalton** [peterarsentev/dionea_bot#26]
Привет, я не знаю собираете ли вы статистику по необработанным сообщениям, но на всякий случай вот:

"Кому интерeснo зaрaбaтывaть кaждый дeнь oт 150$, в oнлaйн фoрмaтe, зa дeтaлями пишитe в лс, с 18 лeт." 
и
"Добрый день! В поиске людей. Удаленная сфера занятости,подойдет каждому. За дополнительной информацией пишите в личку"

в данных сообщениях dionea_bot не видит спама,

**Comment by peterarsentev** [comment]
@leyalton Благодарен за информацию. Бота настроили.

Если буду еще осечки, то пишите. Спасибо.

**Comment by leyalton** [comment]
upd.
Текст сообщения не содержит спама!

Срочно нужен человек на удаленный заработок , с тебя телефон и два часа свободного времени в день, заработок очень достойный " + " в лс
